config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "articles#index"

  resources :articles do
    resources :comments
    collection do
      get '/archived', to: 'articles#archived'
    end
  end

  #get '/articles/archived', to: 'articles#archived' as: :archived_articles
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  include Visible
  belongs_to :author, class_name: 'User'

  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }

  scope :published, ->(value = 'public') { where(status: value) }
  scope :non_published, -> { published('archived') }
  scope :ordered, ->(direction = :desc) { order(created_at: direction) }
  scope :with_authors, -> { includes(:author) } 
end

app/models/comment.rb
class Comment < ApplicationRecord
  include Visible
  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable, , :rememberable
  devise :database_authenticatable, :registerable, :recoverable, :validatable

  has_many :articles, dependent: :destroy, foreign_key: :author_id

  ROLES = {
    user: 0,
    admin: 1
  }.with_indifferent_access.freeze

  enum role: ROLES
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private
  
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  #http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  #before_action :autorize_user!, only: [:edit, :destroy, :update]

  def index
    authorize Article
    @articles = Article.published.ordered.with_authors
  end

  def archived
    authorize Article
    @articles = current_user.admin? ? Article.all : current_user.articles
    @articles = @articles.non_published.ordered.with_authors
  end

  def show
    authorize @article
  end

  def new
    authorize Article
    @article = Article.new
  end

  def create 
    authorize Article
    @article = Article.new(article_params)
    
    @article.author = current_user

    if @article.save
      redirect_to @article 
    else 
      render :new
    end
  end

  def edit
    authorize @article
  end

  def update
    authorize @article
    if @article.update(article_params)
      redirect_to @article
    else
      render :edit
    end
  end

  def destroy
    authorize @article
    @article.destroy

    redirect_to root_path
  end

  private
    def article_params
      params.require(:article).permit(:title, :body, :status);
    end

    def set_article
      @article = Article.find(params[:id])
    end

    #def autorize_user!
    #  return if @article.author_id == current_user.id  
    #  redirect_to :articles, alert: "You don`t have permission to perform this action."
    #end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  #http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy
  before_action :authenticate_user!, only: [:create, :destroy]
  before_action :set_article, only: [:create, :destroy]
  before_action :autorize_user!, only: :destroy

  def create
      @comment = @article.comments.create(comment_params)
      @comment.commenter = @article.author.email
      redirect_to article_path(@article)
  end

  def destroy
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end
  
  private
    def comment_params
      params.require(:comment).permit(:body, :status)
    end

    def set_article
      @article = Article.find(params[:article_id])
    end

    def autorize_user!
      return if @article.author_id == current_user.id  

      redirect_to :articles, alert: "You don`t have permission to perform this action."
    end
end

app/controllers/concerns/visible.rb
module Visible
  extend ActiveSupport::Concern

  VALID_STATUSES = ['public', 'private', 'archived']
  
  included do
    validates :status, inclusion: { in: VALID_STATUSES }
  end

  class_methods do 
    def public_count
      where(status: 'public').count
    end
  end

  def archived?
    status == 'archived'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_articles.html.erb
<ul>
  <% articles.each do |article| %>
    <li>
      <%= link_to article.title, article %> 
    </li> 
  <% end %>
</ul>

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :status %><br>
    <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
  </div>
    
  <div>
    <br><%= form.submit %>
  </div>
<% end %>

app/views/articles/archived.html.erb
<h1>Archived articles</h1>

<%= render 'articles', articles: @articles %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<h1>Articles</h1>

Our blog has <%= Article.public_count %> articles and counting!

<%= render 'articles', articles: @articles %>

<%= link_to "New Article", new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render "form", article: @article %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<p>Created at: <%= @article.created_at %></p>

<p>Created by: <%= @article.author.email %></p>

<p><%= @article.body %></p>

<ul>
  <% if policy(@article).update? %>
    <li><%= link_to "Edit", edit_article_path(@article) %></li>
  <% end %>
  <% if policy(@article).destroy? %>
    <li><%= link_to "Destroy", article_path(@article),
                    method: :delete,
                    data: { confirm: "Are you sure?" } %></li>
  <% end %>
</ul>

<h2>Comments</h2>
<%= render @article.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<% if user_signed_in? && @article.author_id == current_user.id || current_user.admin? %>
  <p>
    <%= link_to 'Destroy Comment', [comment.article, comment],
                method: :delete,
                data: { confirm: "Are you sure?" } %>
  </p>
<% end %>

app/views/comments/_form.html.erb
<%= form_with model: [ @article, @article.comments.build ] do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.label :status %><br>
    <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= link_to "Home", root_path %> | 
      <% if user_signed_in? %>
        <%= link_to "Archived articles", archived_articles_path %>
        |
        <%= current_user.email %> 
        <% if current_user.admin? %>
          (admin)
        <% end %>
        |
        <%= link_to "Log out", destroy_user_session_path, 
                               method: :delete, 
                               data: { confirm: "Are you sure?" } %>
      <% else %>
        <%= link_to "Log in", new_user_session_path %>
      <% end %>
    </header>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
    <%= yield %>
  </body>
</html>